version: '3.8'

services:
  controller:
    image: ngrinder/controller
    container_name: ngrinder-controller
    ports:
      - "8090:80"
    environment:
      TZ: Asia/Seoul
    networks:
      - ngrinder-net

  agent:
    image: ngrinder/agent
    container_name: ngrinder-agent
    depends_on:
      - controller
    environment:
      CONTROLLER_IP: controller
      CONTROLLER_PORT: 80
      AGENT_MODE: agent
    networks:
      - ngrinder-net

networks:
  ngrinder-net:
    driver: bridge
