name: Dev CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: |
          cd FineApple
          ./mvnw clean package -DskipTests
          cd ..

      - name: Build Spring (Spring Server)
        run: |
          docker build -t fineapple-spring-dev ./FineApple

      - name: Build FastAPI
        run: |
          docker build -t fineapple-fastapi-dev ./fastapi-server

      - name: Build Batch
        run: |
          docker build -t fineapple-batch-dev ./batch
