name: Dev CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      IMP_API_KEY: ${{ secrets.IMP_API_KEY }}
      IMP_API_SECRET: ${{ secrets.IMP_API_SECRET }}
      IMPCODE: ${{ secrets.IMPCODE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: |
          cd FineApple
          ./mvnw clean package -DskipTests
          cd ..

      - name: Build Spring (Spring Server)
        run: |
          docker build --build-arg DB_USERNAME=$DB_USERNAME \
                       --build-arg DB_PASSWORD=$DB_PASSWORD \
                       --build-arg DB_URL=$DB_URL \
                       --build-arg IMP_API_KEY=$IMP_API_KEY \
                       --build-arg IMP_API_SECRET=$IMP_API_SECRET \
                       --build-arg IMPCODE=$IMPCODE \
                       -t fineapple-spring-dev ./FineApple

      - name: Build FastAPI
        run: |
          docker build -t fineapple-fastapi-dev ./fastapi-server

      - name: Build Batch
        run: |
          docker build -t fineapple-batch-dev ./batch
